env:
  browser: true
  es2021: true
extends:
  - prettier
  - standard-with-typescript
  - plugin:react/recommended
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
settings:
  import/resolver:
    webpack:
      config: "path/to/your/webpack.config.js"
# other ESLint configurations...
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - typescript-eslint
  - prettier
rules:
  eqeqeq: off
  curly": error
  no-console: 1
  no-unused-vars:
    - error
  prettier/prettier: 2
  quotes:
    - error
    - double
