env:
  browser: true
  es2021: true
extends:
  - prettier
  - standard-with-typescript
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - typescript-eslint
  - prettier
rules:
  eqeqeq: off
  curly": error
  no-console: 1
  no-unused-vars:
    - error
  prettier/prettier: 2
  quotes:
    - error
    - double
