env:
  browser: true
  es2021: true
extends:
  - prettier
  - standard-with-typescript
  - plugin:react/recommended
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
settings:
  import/resolver:
    webpack:
      config: "path/to/your/webpack.config.js"
# other ESLint configurations...
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - typescript-eslint
  - prettier
rules:
  curly": error
  no-console: 1
  no-unused-vars:
    # Possible values: "off", "warn", "error"
    - error
    # Additional options for the rule can be specified here
    - vars: all
    - args: after-used
    - ignoreRestSiblings: true
  eqeqeq: off

  prettier/prettier: 2
  quotes:
    - error
    - double
